### ISSUE TITLE
Re-license this as BSD?

### ISSUE THREAD

**Issue by damianavila** [Cadair/jupyter_environment_kernels#12]
Related with this comment: https://github.com/Cadair/jupyter_environment_kernels/issues/2#issuecomment-189247000

Your license and BSD is pretty much the same and having this one as BSD would be nice for further work based on this one (the ecosystem is mostly using BSD so things keep compatible across the the ecosystem).

Thoughts? @Cadair

**Comment by Cadair** [comment]
It is BSD 2 clause: https://opensource.org/licenses/BSD-2-Clause

**Comment by Cadair** [comment]
Or at least it should be...

**Comment by damianavila** [comment]
Well... this is why I read both as pretty much the same :wink:
Thanks for the clarification!
