### ISSUE TITLE
Finds conda envs, but during notebook startup: throws exception for each 

### ISSUE THREAD

**Issue by paepcke** [Cadair/jupyter_environment_kernels#14]
Your package is exactly what I am looking for, but...

After installing environment_kernels 1.0 from PyPi while in the conda root environment, and setting the following in the jupyter_notebook_config.py:
```
c.NotebookApp.kernel_spec_manager_class = 'environment_kernels.EnvironmentKernelSpecManager'
c.EnvironmentKernelSpecManager.virtualenv_env_dirs=['$HOME/.virtualenv/envs/']
c.EnvironmentKernelSpecManager.conda_env_dirs=['$HOME/anaconda2/envs/']
```
I start:
```
 jupyter notebook. 
```
For each of my conda environments I get the following stack trace. The example here is for an environment called 'paepcke':
```
[E 09:19:41.626 NotebookApp] Failed to load kernel spec: 'paepcke'
    Traceback (most recent call last):
      File "/Users/paepcke/anaconda2/lib/python2.7/site-packages/notebook/services/kernelspecs/handlers.py", line 58, in get
        d = kernelspec_model(self, kernel_name)
      File "/Users/paepcke/anaconda2/lib/python2.7/site-packages/notebook/services/kernelspecs/handlers.py", line 22, in kernelspec_model
        spec = ksm.get_kernel_spec(name)
      File "/Users/paepcke/anaconda2/lib/python2.7/site-packages/environment_kernels/core.py", line 64, in get_kernel_spec
        except (NoSuchKernel, FileNotFoundError):
    NameError: global name 'FileNotFoundError' is not defined
```
It looks like all the environments are found, but they all fail. The notebook does start, but of course, only the default kernels are offered in the Change-kernel item. I also tried using tilde instead of $HOME in the config file; same result.

Where am I going wrong?

Thanks!

Andreas
paepcke@cs.stanford.edu

**Comment by janschulz** [comment]
Please update to a later version (aka master), this should be fixeD: https://github.com/Cadair/jupyter_environment_kernels/commit/222a82977377c49d811e887550b497279e8822f5

**Comment by paepcke** [comment]
Thank you for your lightning-quick response! That did the trick. It's
working.

If you want people to get to running even more smoothly, you
might want to

- add to the readme.me that if people clone master, they have to:

    cp -r <git-root>/environment_kernels
~/anaconda2/lib/python2.7/site-packages

   or wherever their conda root is.
   Unless you can get  "python setup.py install" to do this.

- correct the needed entry in the config file to:

c.NotebookApp.kernel_spec_manager_class =
'environment_kernels.core.EnvironmentKernelSpecManager'

Note the '.core.', which is missing in readme version.

Thank you for this contribution!

Andreas

**Comment by janschulz** [comment]
> add to the readme.me that if people clone master, they have to

actually that is what I thought is happening in setup.py? At least I run `python setup.py install` (with an activated env for my notebook server) and it installs just fine?

> correct the needed entry in the config file to

This shouldn't be nesseary, as `__init__.py` imports this and so it should be available as `environment_kernels.EnvironmentKernelSpecManager`

**Comment by paepcke** [comment]
I'll check it out. I looked at the setup file, and it seemed
all to be metadata for pypi. But I'd also been messing with my
overall setup for a while, so its state may have been off.

As for ... .core ...: it was an exception raised when I started
the server without the .core in the config file. I'll check whether in my
manual
copying I grabbed the wrong __init__.

In either even, I'm quite happy with the working addition!

On Tuesday, May 31, 2016, Jan Schulz <notifications@github.com> wrote:

> add to the readme.me that if people clone master, they have to
>
> actually that is what I thought is happening in setup.py? At least I run python
> setup.py install (with an activated env for my notebook server) and it
> installs just fine?
>
> correct the needed entry in the config file to
>
> This shouldn't be nesseary, as __init__.py imports this and so it should
> be available as environment_kernels.EnvironmentKernelSpecManager
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Cadair/jupyter_environment_kernels/issues/14#issuecomment-222647294>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAl-rEhHmK8N3O85da1B81BCKQMbt0GDks5qHAk2gaJpZM4Ip7a9>
> .
>


-- 
Tapped painstakingly on my mobile device... Andreas

**Comment by paepcke** [comment]
Jan, my apologies: I wiped out my anaconda installation
and your code, and started fresh. Use setup.py, and
it all works. I replicated on both OS X and ubuntu 14.04.

Thanks!

Andreas
