### ISSUE TITLE
Wrong Info in Blog

### ISSUE THREAD

**Issue by paepcke** [Cadair/jupyter_environment_kernels#15]
At http://stuartmumford.uk/blog/jupyter-notebook-and-conda.html you have
out-of-date info:
```
pip install jupyter_environment_kernels
```
Also: the default installation for Anaconda seems now to be: ~/anaconda2.

Andreas

**Comment by koalaGreener** [comment]
Damn true, and if you type the code as the blog illustrated, then you will receive that:

Could not find a version that satisfies the requirement jupyter-environment-kernels (from versions: )
No matching distribution found for jupyter-environment-kernels

**Comment by Cadair** [comment]
I have fixed this now, thanks for the heads up.
