### ISSUE TITLE
Release 1.1?

### ISSUE THREAD

**Issue by Cadair** [Cadair/jupyter_environment_kernels#18]
@janschulz Do you think the changes made with the code from xonsh are good for a relase? I tested it for my setup and it seems to work mostly ok (as long as I keep `use_conda_directly` off see #16 ).

**Comment by janschulz** [comment]
The problem is that I can only test conda on windows. What would be interesting would be tests on

* [ ] virtualenv on windows
* [ ] virtualenv on linux/OSX
* [ ] conda on linux/OSX

**Comment by Cadair** [comment]
is there some way we can get a list of the loaded kernels out of the notebook in an automated way? If we could do that we could setup some CI services to test the configs?

**Comment by janschulz** [comment]
https://github.com/Anaconda-Platform/nb_conda_kernels/tree/master/nb_conda_kernels/tests has some tests via JS and the notebook UI

I guess One could also use jupyter-client directly: https://github.com/janschulz/knitpy/blob/master/knitpy/knitpy.py#L102-L104

```py
from jupyter_client.kernelspec import KernelSpecManager
ksm = KernelSpecManager()
ksm.find_kernel_specs()
```

**Comment by janschulz** [comment]
BTW: thanks for the invitation and the push rights. I'm still happy to contribute only via PRs, I like getting my code reviewed first :-)

**Comment by Cadair** [comment]
Because we have made a few changes recently and we are picking up users I am going to go a do a 1.1 release, so we don't have to tell people to install from git. We should think about tests for the next one though.

**Comment by janschulz** [comment]
@Cadair: Ping :-)

I just had to find out the pip syntax for installing from github to work around the missing release... :-)

**Comment by Cadair** [comment]
I will try and do this next week.

**Comment by janschulz** [comment]
I've tested the setup with conda on linux.

**Comment by Cadair** [comment]
https://pypi.python.org/pypi/environment_kernels/1.1

I have pushed a release, at long long last.

**Comment by janschulz** [comment]
It might be interesting to add a small item in the next jupyter newsletter about the release: https://github.com/jupyter/newsletter/issues

If you want, I can add an issue there :-)

**Comment by Cadair** [comment]
I did not know that existed, please go for it.

We should also try and write up some actual docs for this now that it has a lot of cool features that are unique to it.

**Comment by janschulz** [comment]
https://github.com/jupyter/newsletter/issues/64

**Comment by Cadair** [comment]
ThanksThanks!
