### ISSUE TITLE
Config option `conda_env_dirs` not recognized by `EnvironmentKernelSpecManager`

### ISSUE THREAD

**Issue by chuckwondo** [Cadair/jupyter_environment_kernels#20]
I followed the instructions, and added the following lines to my config:

```
c.NotebookApp.kernel_spec_manager_class = 'environment_kernels.EnvironmentKernelSpecManager'
c.EnvironmentKernelSpecManager.conda_env_dirs = ['~/miniconda3/envs/']
```

When I ran `jupyter notebook`, I received the following warning message:

```
Config option `conda_env_dirs` not recognized by `EnvironmentKernelSpecManager`.  Did you mean `env_dirs`?
```

Therefore, I changed the second config line to match the hint in the warning, and that eliminated the warning. However, I then ran into other errors, which are appropriate for another issue that I'll create.

Regarding this issue, it seems that your instructions in the README are not aligned with the implementation, so this is a request to make sure they're in agreement, either by updating the instructions, or updating the code. I don't know which is incorrect.

**Comment by janschulz** [comment]
Please update to master, the install instruction refer to that version, not the currently releases one on pypi.

**Comment by chuckwondo** [comment]
I cloned the repo, and built and installed via `setup.py`, but I'm a noob regarding doing such things with Python. I don't know how to build and install a package from source, and then install it into a particular environment (I'm using condo envs). Would you mind pointing me in the right direction?

**Comment by janschulz** [comment]
* Activate the env where you have the jupyter notebook installed (if root, you usually don't need to activate anything), otherwise `conda activate name_of_notebook_env`
* call `python setup.py install` (instead of `pip install environment_kernels`)
* Do the config steps as stated in the README

done :-)

**Comment by chuckwondo** [comment]
Thanks! That worked. I now see the kernels listed, and they appear to be working correctly, as far as I've checked.

However, the terminal window still dumps the following for each environment it discovers:

```
[E 20:20:51.870 NotebookApp] Couldn't get environment variables for commands: ['activate', u'/Users/charlie/miniconda3/envs/coursera-ml-regression']
    Traceback (most recent call last):
      File "build/bdist.macosx-10.6-x86_64/egg/environment_kernels/core.py", line 296, in _get_env_vars_for_conda_env
        return _source_env_vars_from_command(args)
      File "build/bdist.macosx-10.6-x86_64/egg/environment_kernels/core.py", line 41, in _source_env_vars_from_command
        return source_zsh(args)
      File "build/bdist.macosx-10.6-x86_64/egg/environment_kernels/activate_helper.py", line 49, in source_zsh
        return source_foreign(new_args, stdin=stdin)
      File "build/bdist.macosx-10.6-x86_64/egg/environment_kernels/activate_helper.py", line 151, in source_foreign
        seterrpostcmd=ns.seterrpostcmd)
      File "build/bdist.macosx-10.6-x86_64/egg/environment_kernels/activate_helper.py", line 394, in foreign_shell_data
        except (subprocess.CalledProcessError, FileNotFoundError):
    NameError: global name 'FileNotFoundError' is not defined
```

I'm using Python 2.7.12 in the activated environment, and I have the following in my Jupyter config file:

```
c.NotebookApp.kernel_spec_manager_class = 'environment_kernels.EnvironmentKernelSpecManager'
c.EnvironmentKernelSpecManager.conda_env_dirs = ['~/miniconda3/envs/']
```

**Comment by janschulz** [comment]
I tried to fix that in #22 (the first commit)...

**Comment by chuckwondo** [comment]
Nice. Thanks for the work. I'll keep my eyes peeled for your PR getting accepted.

**Comment by janschulz** [comment]
This has landede quite some time ago
