### ISSUE TITLE
Failed to load kernel spec in Python 2.7

### ISSUE THREAD

**Issue by chuckwondo** [Cadair/jupyter_environment_kernels#21]
I have the following lines in my config, as per the instructions (although I had to change `condo_env_dirs` to `env_dirs`):

```
c.NotebookApp.kernel_spec_manager_class = 'environment_kernels.EnvironmentKernelSpecManager'
c.EnvironmentKernelSpecManager.env_dirs = ['~/miniconda3/envs/']
```

When I run `jupyter notebook` (with an activated environment), I receive the following error for every environment that the plugin found (where `ENV-NAME` is the name of the discovered environment, and CURRENT-ENV is the currently active environment):

```
[E 21:45:48.870 NotebookApp] Failed to load kernel spec: 'ENV-NAME'
    Traceback (most recent call last):
      File "/Users/charlie/miniconda3/envs/CURRENT-ENV/lib/python2.7/site-packages/notebook/services/kernelspecs/handlers.py", line 58, in get
        d = kernelspec_model(self, kernel_name)
      File "/Users/charlie/miniconda3/envs/CURRENT-ENV/lib/python2.7/site-packages/notebook/services/kernelspecs/handlers.py", line 22, in kernelspec_model
        spec = ksm.get_kernel_spec(name)
      File "/Users/charlie/miniconda3/envs/CURRENT-ENV/lib/python2.7/site-packages/environment_kernels/core.py", line 64, in get_kernel_spec
        except (NoSuchKernel, FileNotFoundError):
    NameError: global name 'FileNotFoundError' is not defined
```

When I updated my environment to use Python 3, everything works. Unfortunately, I am using a package that requires Python 2.7. It appears this plugin requires Python 3. Is that correct, or do you expect it to work in Python 2 as well?

**Comment by janschulz** [comment]
Please update to master here, the python3/2 is fixed and that probably also fixes the `env_dirs` problem

**Comment by janschulz** [comment]
This is fixed in the latest issue, please update.

I'm closing this issue. If you still have problems, please reopen the issue
