### ISSUE TITLE
Support R kernels

### ISSUE THREAD

**Issue by Cadair** [Cadair/jupyter_environment_kernels#23]
I notice that https://github.com/Anaconda-Platform/nb_conda_kernels/blob/master/nb_conda_kernels/manager.py#L47 goes hunting for R in conda envs, this is something we could also support. As well as that maybe other langs? Juila etc?

**Comment by janschulz** [comment]
I also thought about it... The biggest problem I have is that currently we assume that all envs are also capable of running a kernel (no matter if python or R). In my environment, this is not the case, so recently I have had a lot of "Kernel couldn't be started" kind of problems, which in the end are "Oh, I forget to install the ipykernel package" or "Oh d**n, I clicked the wrong kernel" problems...

Currently doing a refactoring to make supporting multiple kernel types easier... Will probably do a PR today...
