### ISSUE TITLE
Duplicate env kernels

### ISSUE THREAD

**Issue by yech1990** [Cadair/jupyter_environment_kernels#27]
```bash
[E 02:45:37.012 NotebookApp] Duplicate env kernels: conda_qiime1 
would both point to (
'/usr/local/lib/python3.5/dist-packages/environment_kernels/logos/python',
 <jupyter_client.kernelspec.KernelSpec object at 0x7f04b1740710>) and 
/home/yc/.anaconda3/envs/qiime1. Using the first!

```

**Comment by janschulz** [comment]
Apart from the `logos` part I see no problem: This means either that it found a kernel in the same environment were the notebook server was installed (The notebook server adds the current python as the default kernel) or that the kernel for that environment was installed manually.

@yech1990 What did you expect to happen?

**Comment by yech1990** [comment]
I expect jupyter to use the python for virtual environment.

I have some script in the path, and  I can call the script directly when I active anaconda envs.
But when I  activate jupyter notebook with the kernel that  `jupyter_environment_kernels` create, I can't find those script in the path.

**Comment by janschulz** [comment]
You might try the latest PR in https://github.com/Cadair/jupyter_environment_kernels/pull/29: I had an embarrassing bug in the activation code (it's 'source activate ...' on unix, not 'activate...')

**Comment by janschulz** [comment]
This should be fixed by the new release, please upgrade.

I'm closing this issue, please reopen if you still have problems.
