### ISSUE TITLE
Should look for *\Scripts\ipython.exe on windows

### ISSUE THREAD

**Issue by janschulz** [Cadair/jupyter_environment_kernels#3]
My `ipython.exe` file is in `C:\portabel\miniconda\envs\knitpy_27\Scripts\` and thats the path that is added to `%path%` be activate: https://github.com/conda/conda-env/blob/develop/bin/activate.bat#L63

**Comment by Cadair** [comment]
Would you be willing to test my implementation of this in master?

**Comment by JanSchulz** [comment]
See the PR... Seems like windows and unix are quite different :-(
