### ISSUE TITLE
calling jupyter notebook outputs error

### ISSUE THREAD

**Issue by jshin49** [Cadair/jupyter_environment_kernels#33]
calling

```bash
jupyter notebook --NotebookApp.kernel_spec_manager_class='environment_kernels.EnvironmentKernelSpecManager'
```

causes this error:

```
[C 15:15:03.610 NotebookApp] Bad config encountered during initialization:
[C 15:15:03.610 NotebookApp] The 'kernel_spec_manager_class' trait of <notebook.notebookapp.NotebookApp object at 0x10314af90> instance must be a type, but u'environment_kernels.EnvironmentKernelSpecManager' could not be imported
```

How should I deal with this issue?

**Comment by Cadair** [comment]
`'environment_kernels.EnvironmentKernelSpecManager' could not be imported`

It appears from this line that there is something wrong with your install, are you sure you have this pacakge and your notebook server installed in the same env?

**Comment by Avik1993** [comment]
I am facing the same error. Any way to rectify this?

**Comment by driesbuyck** [comment]
I have the same problem. Is this plugin working in python 3.6 environments ?

import environment_kernels
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<removed>/.conda/envs/myenv/lib/python3.6/site-packages/environment_kernels/__init__.py", line 2, in <module>
    from .core import *
  File "<removed>/.conda/envs/myenv/lib/python3.6/site-packages/environment_kernels/core.py", line 7, in <module>
    from jupyter_client.kernelspec import (KernelSpecManager, NoSuchKernel)
ModuleNotFoundError: No module named 'jupyter_client'

**Comment by driesbuyck** [comment]
got this fixed by installing juypiter notebook inside the new conda environment  (conda install jupyter)

**Comment by Cadair** [comment]
You will have to have `environment_kernels` installed in the Python env (conda, virtualenv or system) where you are running the `jupyter notebook` command. Is that what you are saying you fixed, or are you having startup issues if you don't have `jupyter` installed in all your envs?

**Comment by driesbuyck** [comment]
Yes, I had environment_kernels installed in a conda environment, but the jupyter notebook I seem to be starting it from the system. So after installing jupyter notebook inside the conda env, it fixed.  
(I could probably also have installed environment_kernels in system env to get rid of the issue, but it's cleaner inside the conda environment)

**Comment by Cadair** [comment]
maybe this needs to be a little better documented (much like the whole project), but the solution to this, as you have found, is to have both the notebook server and environment_kernels installed in the same path.

**Comment by Darshil020** [comment]
i tried installing jupyter notebook inside my environment. it is still not working.

**Comment by buddhashrestha** [comment]
You need to install environment_kernels using :
`pip install environment_kernels`

**Comment by xiaoleitw** [comment]
facing the same question.

**Comment by nocibambi** [comment]
Same issue. I cannot run `jupyter notebook` from the system (but it works from another environment).

[Here][1], someone solved by editing the config, but did not specify which one.

[1]: https://github.com/Anaconda-Platform/nb_conda_kernels/issues/63#issuecomment-279586354

**Comment by nocibambi** [comment]
> Same issue. I cannot run `jupyter notebook` from the system (but it works from another environment).
> 
> [Here](https://github.com/Anaconda-Platform/nb_conda_kernels/issues/63#issuecomment-279586354), someone solved by editing the config, but did not specify which one.

Ok, so I solved it finally, here are the steps:
1. In terminal, find the configurations directories with `jupyter --paths`.
2. In one of the directories there I found `jupyter_notebook_config.json`
3. Save a back up copy ;)
4. From the file delete the following line:
```json
"kernel_spec_manager_class": "nb_conda_kernels.CondaKernelSpecManager" 
```
5. Delete the comma preceding it. (Duh, I know...)

**Comment by TPVasconcelos** [comment]
Some specs:
- Ubuntu 18.04.1 LTS
- conda 4.6.3
- Python 3.7.1

It might not work for everyone but I solved this issue by activating my environment via
```bash
$ source activate myenv
```
instead of
```bash
$ conda activate myenv
```
before running
```bash
$ jupyter notebook
```

**Comment by InsciteAnalytics** [comment]
@nocibambi 
My friend, I owe you my sanity ;)
Thanks so much!

**Comment by lstamaria** [comment]
@nocibambi 
This actually works. Amazing. Thank you!

**Comment by Djeutsch** [comment]
> > Same issue. I cannot run `jupyter notebook` from the system (but it works from another environment).
> > [Here](https://github.com/Anaconda-Platform/nb_conda_kernels/issues/63#issuecomment-279586354), someone solved by editing the config, but did not specify which one.
> 
> Ok, so I solved it finally, here are the steps:
> 
> 1. In terminal, find the configurations directories with `jupyter --paths`.
> 2. In one of the directories there I found `jupyter_notebook_config.json`
> 3. Save a back up copy ;)
> 4. From the file delete the following line:
> 
> ```json
> "kernel_spec_manager_class": "nb_conda_kernels.CondaKernelSpecManager" 
> ```
> 
> 1. Delete the comma preceding it. (Duh, I know...)

Many thanks for this.

**Comment by PursuitYP** [comment]
@nocibambi It really works! Thank you very much!

**Comment by andreisharshov** [comment]
@nocibambi Thank you very much!:)

**Comment by HashRocketSyntax** [comment]
my `jupyter_notebook_config.json` file was in `/opt/conda/envs/beakerx/etc/jupyter`

**Comment by sykim862** [comment]
@Djeutsch Thank you very much ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

**Comment by jamesmuniu** [comment]
Thank you!!

**Comment by ctawong** [comment]
For error that cannot import 

` nb_conda_kernels.CondaKernelSpecManager`

It was because nb_conda_kernels cannot be imported. That can happy when you change environment that calls juypter notebook.

`conda install nb_conda_kernels` resolves the problem.

**Comment by coolkate3738** [comment]
@nocibambi  you are a real hero!! Big love <3

**Comment by minying1999** [comment]
> > Same issue. I cannot run `jupyter notebook` from the system (but it works from another environment).
> > [Here](https://github.com/Anaconda-Platform/nb_conda_kernels/issues/63#issuecomment-279586354), someone solved by editing the config, but did not specify which one.
> 
> Ok, so I solved it finally, here are the steps:
> 
> 1. In terminal, find the configurations directories with `jupyter --paths`.
> 2. In one of the directories there I found `jupyter_notebook_config.json`
> 3. Save a back up copy ;)
> 4. From the file delete the following line:
> 
> ```json
> "kernel_spec_manager_class": "nb_conda_kernels.CondaKernelSpecManager" 
> ```
> 
> 1. Delete the comma preceding it. (Duh, I know...)

Thank you very much, you are such a hero!

**Comment by sreedharu** [comment]
> > Same issue. I cannot run `jupyter notebook` from the system (but it works from another environment).
> > [Here](https://github.com/Anaconda-Platform/nb_conda_kernels/issues/63#issuecomment-279586354), someone solved by editing the config, but did not specify which one.
> 
> Ok, so I solved it finally, here are the steps:
> 
> 1. In terminal, find the configurations directories with `jupyter --paths`.
> 2. In one of the directories there I found `jupyter_notebook_config.json`
> 3. Save a back up copy ;)
> 4. From the file delete the following line:
> 
> ```json
> "kernel_spec_manager_class": "nb_conda_kernels.CondaKernelSpecManager" 
> ```
> 
> 1. Delete the comma preceding it. (Duh, I know...)

Thank you

**Comment by scott-n58** [comment]
this issue seems to be a problem with nb extensions becoming corrupted.
https://docs.anaconda.com/anaconda/user-guide/tasks/use-jupyter-notebook-extensions/
reviewing this setting after following the deletion step from above I did get 
a notebook session successfully started. of course - w/o my envs. 
to resolve this i found the link above & in an open notebook cell:
conda install nb_conda
after this was completed (w/o any hiccups) i checked that *_config.json file
& sure enough:
in this  jupyter_notebook_config.json was the new extension seek line
with nb_conda set to true.

{
"NotebookApp": {
"nbserver_extensions": {
         "nb_conda": true
          },
           "kernel_spec_manager_class': "nb_conda_kernels.CondaKernelSpecManager"
}

**Comment by Larry-u** [comment]
> this issue seems to be a problem with nb extensions becoming corrupted.
> https://docs.anaconda.com/anaconda/user-guide/tasks/use-jupyter-notebook-extensions/
> reviewing this setting after following the deletion step from above I did get
> a notebook session successfully started. of course - w/o my envs.
> to resolve this i found the link above & in an open notebook cell:
> conda install nb_conda
> after this was completed (w/o any hiccups) i checked that *_config.json file
> & sure enough:
> in this jupyter_notebook_config.json was the new extension seek line
> with nb_conda set to true.
> 
> {
> "NotebookApp": {
> "nbserver_extensions": {
> "nb_conda": true
> },
> "kernel_spec_manager_class': "nb_conda_kernels.CondaKernelSpecManager"
> }
> 
> closing with a restart - the new session displayed all of my envs & available for selection.

The analysis from this bro is correct, if u just delete 
```
"kernel_spec_manager_class': "nb_conda_kernels.CondaKernelSpecManager"
```
from `jupyter_config.json`, the error is gone but u cannot see envs in jupyter starter page.

The correct way is delete that line in `jupyter_config.json`, and append it to `jupyter_notebook_config.json` (in the same dir), as the this quote displayed.

**Comment by KonWys01** [comment]
If someone has this issue in case of ArcGIS Pro, then removing ```"kernel_spec_manager_class': "nb_conda_kernels.CondaKernelSpecManager"``` from ```jupyter_config.json``` solves the issue (in default environment -```C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\etc\jupyter```.

If you are not allowed to do it - grand yourself all roles in ```properties -> security -> users```. You need administrator account to do it

**Comment by mugsiemx** [comment]
SOLVED!! THANK YOU so very much!! my path is;  C:\Users\<username>\anaconda3\etc\jupyter\jupyter_notebook_config.json. Once deleting the "kernel_spec_manager_class': "nb_conda_kernels.CondaKernelSpecManager" line from the file, my jupter notebook fired up quickly!!  I AM SO GRATEFUL!!
