### ISSUE TITLE
Please add support of pyenv python versions

### ISSUE THREAD

**Issue by chasylexus** [Cadair/jupyter_environment_kernels#38]
It will be very useful to work with different pyenv python versions located in `˜/.pyenv/versions/`.

**Comment by Cadair** [comment]
How does pyenv interact with virtualenv? This package tries to find an ipython executable as a way of detecting where the python executable is. So If you have a virtualenv of some kind pointing at a pyenv executable it *should* work?

I haven't tried pyenv, but I am happy to get this working with it.

**Comment by chasylexus** [comment]
Idon't use virtualenv, it event had not been installed on my computer. I use only pyenv and it can work without virtualenv.
Now I installed jupyter_environment_kernels but it doesn't take effect: jupyter can't see python additional kernels, it see only global python version that have been set by pyenv.

**Comment by Cadair** [comment]
Forgive my ignorance, I have not used pyenv before. In `~/.pyenv/versions/...` do you have a folder structure that looks like this:
```
./<version1>/bin/ipython
./<version2>/bin/ipython
```

If so, you should be able to configure the virtualenv support in this package to point at your `.pyenv/versions` directory rather than the standard virtualenv ones. This is because there is a mode that this can work in where it will search for ipython executables to detect environments to turn into kernels.

**Comment by chasylexus** [comment]
Thank you very much for answer!
Yes, the folder structure is exactly as you described.
OK, I'll change virtualenv support but maybe in future it will be useful to make sort of built-in support of pyenv.

**Comment by chasylexus** [comment]
It works but not perfect. On my computer I've installed via pyenv two versions of python: 3.7.1 and 2.7.15. Jupyter was installed via 3.7.1's pip so it see python 3.7.1 kernel out of the box. After setting up config of jupyter_environment_kernels in way when jupyter see both installed kernels I have two main issues:
1. it doubles python 3.7.1: just as Python and also as "Environment (virtualenv_3.7.1).
2. the names of kernels are too long and include "virtualenv". For example in Jupyter lab you can't see full names of kernels (see screenshots).
Jupyter:
![#1](https://imgur.com/2axKVNr.png)
Jupyter Lab:
![#2](https://i.imgur.com/IseiTIl.png)

**Comment by Cadair** [comment]
The duplication of the Python 3 I am not sure you can avoid. You can customise the template for the name though:

for example setting this: 
```
c.EnvironmentKernelSpecManager.virtual_prefix_template = "{}"
```
would just use the version number.

**Comment by chasylexus** [comment]
Thank you!
Addind of `c.EnvironmentKernelSpecManager.virtualenv_prefix_template = "{}"` line works but now names are like "Environment (3.7.1)" instead of  "Environment (virtualenv_3.7.1)".
Is there any way to make name look like version number only?

**Comment by Cadair** [comment]
ah that's 

```
c.EnvironmentKernelSpecManager.virtual_name_template = "{}"
```
I think

**Comment by chasylexus** [comment]
Unfortunately this doesn't take an effect.

**Comment by Cadair** [comment]
oh it should be:

```
c.EnvironmentKernelSpecManager.display_name_template = "{}"
```

**Comment by chasylexus** [comment]
OK!
Finally, here is instruction:
1. Generate config file if not yet:
`jupyter notebook --generate-config`
2. Add following lines to the end of the file:
```
c.NotebookApp.kernel_spec_manager_class = 'environment_kernels.EnvironmentKernelSpecManager'
c.EnvironmentKernelSpecManager.virtualenv_env_dirs=['~/.pyenv/versions/']
c.EnvironmentKernelSpecManager.virtualenv_prefix_template = "{}"
c.EnvironmentKernelSpecManager.display_name_template = "{}"
```
This works for Jupyter Lab!
The only problem is that default python appears twise in kernels list with two different names.
