### ISSUE TITLE
On windows, use CONDA_ENVS_PATH env var to look for conda environments

### ISSUE THREAD

**Issue by JanSchulz** [Cadair/jupyter_environment_kernels#4]
on windows, the dir, where conda envs are created on default, is saved in the env var `CONDA_ENVS_PATH`. It would be nice if that could be used as default on windows.

**Comment by danielballan** [comment]
or `conda-env list --json`

**Comment by Cadair** [comment]
Interestingly it seems that `conda-env list` only shows envs in the normal directories, i.e. doing this:

```
conda env create -p ~/testenv python=2 jupyter
conda-env list --json                     
{
  "envs": [
    "/opt/miniconda/envs/nikola",
    "/opt/miniconda/envs/numba",
    "/opt/miniconda/envs/sunpy-dev",
    "/opt/miniconda/envs/sunpy-release",
    "/opt/miniconda/envs/thesis"
  ]
}
```

Thanks for the idea though, I will have a play.

**Comment by JanSchulz** [comment]
Conda list only iterates over all prefixes: https://github.com/conda/conda-env/blob/develop/conda_env/cli/main_list.py#L32 -> https://github.com/conda/conda/blob/master/conda/cli/common.py#L623 https://github.com/conda/conda/blob/master/conda/misc.py#L349 which gets the envs_dirs from the variable: https://github.com/conda/conda/blob/master/conda/config.py#L158

So making the equivalent of `ls %CONDA_EVVS_DIR`.

**Comment by Cadair** [comment]
ahh useful, I will just import `conda.config.envs_dirs` and add it to the list of default directories. Which will work nicely as long as you are running the notebook inside a conda env.

**Comment by JanSchulz** [comment]
This sin't going to work if you use a env for the notebook server itself:

```
λ activate ipython-notebook
Activating environment "C:\portabel\miniconda\envs\ipython-notebook"...

[ipython-notebook] C:\Users\jschulz>python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Nov  7 2015, 13:21:48) [MSC v.1600 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.
>>> import conda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'conda'
```

**Comment by Cadair** [comment]
Fair enough, it is still optional, so it's an added bonus if you are running from the root env.

**Comment by Cadair** [comment]
Between looking for `CONDA_ENV_PATH` if you are in a env and looking for `import conda` if you are in the root env, that should get you part of the way to having the default path configured.
