### ISSUE TITLE
Remove already set kernels before adding kernel specs

### ISSUE THREAD

**Issue by JanSchulz** [Cadair/jupyter_environment_kernels#8]
I've added a few conda kernels manually, so right now some environments turn up twice. It would be nice if the initial checks could look if the complete kernel argument is already in some of the already setup kernels.

**Comment by Cadair** [comment]
I think it would be best if you just black list those environments manually. It's a bit of an edge case?

**Comment by JanSchulz** [comment]
Yes, I think I agree and will actually remove all my currently added kernels for specific envs :-)
