### ISSUE TITLE
Make kernel names unique

### ISSUE THREAD

**Issue by janschulz** [Cadair/jupyter_environment_kernels#9]
I've a conda env called "sc" and a kernel with the same name. In my overview list, only the kernel from the environment (`Environment(sc)`) shows up.

IMO:
* the kernels from the environment should get a prefix, so it's not as easy to get a duplicated kernel name (and maybe a check that if the same is still already in the list, add a postfix)
* The kernel manager should, if a duplicated name is produced, result in the *original* kernel being seen

**Comment by Cadair** [comment]
interesting, where is the sc kernel? I have not experienced it not finding existing kernels before.

**Comment by JanSchulz** [comment]
there is a normal kernel (`C:\Users\<user>\AppData\Roaming\jupyter\kernels\sc\kernel.json`) and there is a conda env in `C:\portabel\miniconda\envs\sc`. The second "wins" at least in the UI: `Environment (sc)` instead of `social capital` as I named that entry in the `kernel.json` file.

**Comment by JanSchulz** [comment]
So in this case it's not so much "not finding it" (the kernel.json points to that conda env...), but using the wrong kernel spec.

**Comment by Cadair** [comment]
OK I see the bug, will try and patch it later.

**Comment by JanSchulz** [comment]
The workaround does not work: the notebook gets the list of directories and here the last element is again the the short name: `C:\portabel\miniconda\envs\sc` and results in a call to `get_kernel_spec("sc")` and not `env_sc`. The interesting thing is that it is listing the kernels as an environment (as in `find_kernel_specs` the environments update the original list) but the kernel spec is loaded from the kernel dir and not the env (as in `get_kernel_spec` it loads the envs only when the call for a kernel in the kernel dir fails but in this case it does not).

I think it would be better to use a arbitrary prefix + env name (like `environmentkernels\conda\name`) and let `find_kernel_specs` return that.
